name: Auto Fetch Playlist

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */2 * * *"   # tiap 30 menit
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch playlist (only LIVE)
        run: |
          curl -L --max-time 60 \
            -H "User-Agent: Mozilla/5.0" \
            -H "Referer: https://google.com" \
            "http://ogibonetv.diskon.cloud/scriptYouTube.php" \
          | grep -v "\[OFFLINE\]" \
          | grep -v "localhost/offline.mp4" \
          > playlist.m3u

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add playlist.m3u
          git commit -m "Auto update playlist (LIVE only)" || echo "No changes"
          git push
